name: Prettifying

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "publication/**"
      - "Archive/**"

permissions:
  contents: write

jobs:
  prettier:
    name: Check coding style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Nerixyz/actionsx-prettier@v3-adj
        with:
          args: --check .
